/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiTest: typeof import('./src/components/ApiTest.vue')['default']
    BasicConditionIcon: typeof import('./src/components/BasicConditionIcon.vue')['default']
    BasicForecastCard: typeof import('./src/components/BasicForecastCard.vue')['default']
    BasicGlassWrapper: typeof import('./src/components/BasicGlassWrapper.vue')['default']
    BasicHorizontalDivider: typeof import('./src/components/BasicHorizontalDivider.vue')['default']
    BasicLoader: typeof import('./src/components/BasicLoader.vue')['default']
    BasicLocationItem: typeof import('./src/components/BasicLocationItem.vue')['default']
    BasicQualityCard: typeof import('./src/components/BasicQualityCard.vue')['default']
    BasicQualityMonitor: typeof import('./src/components/BasicQualityMonitor.vue')['default']
    BasicSearch: typeof import('./src/components/BasicSearch.vue')['default']
    BasicSearchMessage: typeof import('./src/components/BasicSearchMessage.vue')['default']
    BasicStatCard: typeof import('./src/components/BasicStatCard.vue')['default']
    BasicStatIcon: typeof import('./src/components/BasicStatIcon.vue')['default']
    BasicStatTitle: typeof import('./src/components/BasicStatTitle.vue')['default']
    BasicTemperature: typeof import('./src/components/BasicTemperature.vue')['default']
    BasicTextInput: typeof import('./src/components/BasicTextInput.vue')['default']
    BasicVerticalDivider: typeof import('./src/components/BasicVerticalDivider.vue')['default']
    BasicWeatherStats: typeof import('./src/components/BasicWeatherStats.vue')['default']
    CurrentDateInfo: typeof import('./src/components/CurrentDateInfo.vue')['default']
    ForecastCardSwiper: typeof import('./src/components/ForecastCardSwiper.vue')['default']
    GeoLocationButton: typeof import('./src/components/GeoLocationButton.vue')['default']
    ItemListWrapper: typeof import('./src/components/ItemListWrapper.vue')['default']
    LocationInterface: typeof import('./src/components/LocationInterface.vue')['default']
    MainInfo: typeof import('./src/components/MainInfo.vue')['default']
    MeasurementToggler: typeof import('./src/components/MeasurementToggler.vue')['default']
    QualityCards: typeof import('./src/components/QualityCards.vue')['default']
    StatCards: typeof import('./src/components/StatCards.vue')['default']
    SwiperButton: typeof import('./src/components/SwiperButton.vue')['default']
  }
}
